name: moodai
description: flutter project that detect faciial detection

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  camera: ^0.10.4
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.6.0
  rename: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
